//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.19 at 11:39:42 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws/booking/models")
package ws.booking.models;
